quiz_module_app/forms.py
from tkinter import Button
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, IntegerField, SubmitField, BooleanField,FieldList,Form,FormField
from wtforms.validators import DataRequired, Length

class QuizForm(FlaskForm):
    title = StringField('Tytuł', validators=[DataRequired(), Length(max=100)])
    description = TextAreaField('Opis', validators=[Length(max=500)])
    num_questions = IntegerField('Number of Questions', validators=[DataRequired()])
    questions = FieldList(TextAreaField('Questions',validators=[DataRequired(),Length(max=4)]))
    answers = FieldList(TextAreaField('Answers',validators=[DataRequired(),Length(max=4)]))
    submit = SubmitField('Create Quiz')

class AnswerForm(Form):
    text = StringField('Answer', validators=[DataRequired(), Length(max=100)])
    is_correct = BooleanField('Correct?')
    submit = SubmitField('Add Answer Form')

class QuestionForm(FlaskForm):
    question_text = TextAreaField('Question', validators=[DataRequired(), Length(max=500)])
    answers = FieldList(FormField(AnswerForm),min_entries=1,max_entries=4)
    submit = SubmitField('Add QuestionForm')

class QuizView(Form):
    title = StringField('Title', validators=[DataRequired(), Length(max=100)])
    description = TextAreaField('Description', validators=[Length(max=500)])
    #solve = Button('Create Quiz')

quiz_module_app/routes.py
import string
from flask import Blueprint, render_template, flash, redirect, url_for, request, flash, json, session
from sqlalchemy import MetaData

from .extensions import db
from .models import Question, Quiz, Answer
from .forms import QuizForm, QuestionForm, AnswerForm


main = Blueprint('main', __name__)


@main.route("/add/quiz/json", methods=['POST'])
def add_quiz_json():
    response_arr = json.loads(request.data)
    quiz_title_desc = response_arr[0]
    questions_arr = response_arr[1]
    answers_arr = response_arr[2]
    titleFromJson = quiz_title_desc.get('title')
    descriptionFromJson = quiz_title_desc.get('description')
    print(titleFromJson," ",descriptionFromJson)
    new_quiz = Quiz(title=titleFromJson, description=descriptionFromJson)
    try:
        db.session.add(new_quiz)
        db.session.commit()
    except:
        return 'Nie udało sie zapisac quizu!'

    for question_object in questions_arr:
        new_question = Question(text=question_object.get(
        'question_text'), quiz_id=new_quiz.id)
        try:
            db.session.add(new_question)
            db.session.commit()
        except:
            return 'Nie udało sie zapisac pytania!'
        print("question_object: ",question_object)
        for answer_object in answers_arr:
            tempIsCorrect = False
            print("answer_object: ",answer_object)
            if (answer_object.get('answerToQuestion') == question_object.get('id')):
                if (answer_object.get('is_correct') == "1"):
                    tempIsCorrect = True
                new_answer = Answer(text=answer_object.get('answer_text'), is_correct=tempIsCorrect, 
                                        question_id=new_question.id)
                try:
                    db.session.add(new_answer)
                    db.session.commit()
                except:
                    return 'Nie udało sie zapisac odpowiedzi!'

    return redirect('/')


@main.route('/solve/quiz/<int:quiz_id_parameter>', methods=['POST', 'GET'])
def solve_quiz(quiz_id_parameter):
    quiz = Quiz.query.filter_by(id=quiz_id_parameter).first()
    questions = Question.query.filter_by(quiz_id=quiz.id).all()
    score = 0
    if request.method == 'POST':
        correct_answers = []
        user_answers = []
        if len(questions)==0:
            return render_template('display_score.html', score='Ciężko powiedzieć')
        for question in questions:
            answers = Answer.query.filter_by(question_id=question.id).all()
            if len(answers)==0:
                return render_template('display_score.html', score='Ciężko powiedzieć')
            for answer in answers:
                if answer.is_correct is True:
                    correct_answers.append(answer.id)
            print('correct_answers: ', correct_answers)
            print('request.form.getlist(question.id): ',
                  request.form.getlist(str(question.id)))
            for user_answer in request.form.getlist(str(question.id)):
                user_answers.append(int(user_answer))
        incorrect_user_answers = 0
        if len(user_answer) > len(correct_answers):
            incorrect_user_answers = len(user_answer) - len(correct_answers)
        score = score + len(list(set(correct_answers).intersection(user_answers))) - incorrect_user_answers    
        return render_template('display_score.html', score=score)
    else:
        return render_template('quiz_solve.html', quiz=quiz, questions=questions)


@main.route('/add/answer/<int:question_id_parameter>', methods=['POST', 'GET'])
def add_answer(question_id_parameter):
    question = Question.query.filter_by(id=question_id_parameter).first()
    if request.method == 'POST':
        is_answer_correct = False
        if request.form.get('answer_chk'):
            is_answer_correct = True
        new_answer = Answer(
            text=request.form['answer_text'], is_correct=is_answer_correct, question_id=question.id)
        try:
            db.session.add(new_answer)
            db.session.commit()
            return redirect(url_for('main.edit_quiz', quiz_id_parameter=question.quiz_id))
        except:
            return 'There was an issue adding your task'

    else:
        return render_template('add_answer.html', question=question)


@main.route('/delete/quiz/<int:quiz_id_parameter>')
def delete_quiz(quiz_id_parameter):
    quiz_to_delete = Quiz.query.get_or_404(quiz_id_parameter)
    try:
        db.session.delete(quiz_to_delete)
        db.session.commit()
        flash(f"Deleted quiz with id: {quiz_id_parameter}")
        return redirect('/')
    except:
        return 'There was an issue deleting quiz'


@main.route('/edit/quiz/<int:quiz_id_parameter>', methods=['POST', 'GET'])
def edit_quiz(quiz_id_parameter):

    quiz = Quiz.query.filter_by(id=quiz_id_parameter).first()
    questions = Question.query.filter_by(quiz_id=quiz.id).all()
    

    if request.method == 'POST':
        quizTile = format(request.form['quizTitle'])
        quizDescription = format(request.form['quizDescription'])

        #try:
        if questions:
            a = questions[0].id
            for question in questions:
                c = 0
                question.text = format(request.form['questionText'+str(a)])
                a += 1
                answers = Answer.query.filter_by(question_id=question.id).all()

                if answers:
                    for answer in answers:
                        b = answers[c].id
                        c += 1
                        answer.text = format(request.form['answerText'+str(b)])

                        is_answer_correct = False
                        if (request.form.get('answerBox'+str(b)) == "1"):
                             is_answer_correct = True
                        answer.is_correct = is_answer_correct

        quiz.title = quizTile
        quiz.description = quizDescription
        db.session.commit()
        return redirect('/')
        #except:
            #return 'There was an issue adding your task'

    else:
        return render_template('quiz_edit.html', quiz=quiz, questions=questions)


@main.route('/', methods=['GET','POST'])
def index():
    
    if request.method == 'POST':
       searched_quiz = format(request.form['searchQuiz'])
       quizes = Quiz.query.filter(Quiz.title.ilike(f'%{searched_quiz}%')).all()
       return render_template('index.html', quizes=quizes)
    else:
        quizes = Quiz.query.all()
        return render_template('index.html', quizes=quizes)


@main.route('/quiz/create/', methods=['GET'])
def quiz_create():
    quizForm = QuizForm()
    return render_template('quiz_create.html', form=quizForm)

quiz_module_app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My App{% endblock %}</title>
    <link rel="stylesheet" href="static/style.css" type="text/css">
    <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@700&family=Patrick+Hand&family=Roboto+Condensed&family=Rubik+Microbe&display=swap" rel="stylesheet">
    {% block head %}{% endblock %}
</head>
<body>
    <header>
        <nav id="navigation-bar">
            <ul>
                <li class="logo"></li>
                <li><a href="{{ url_for('main.index') }}">Strona Główna - Lista Quizów</a></li>
                <li><a href="{{ url_for('main.quiz_create') }}">Stwórz swój własny Quiz!</a></li>
            </ul>
        </nav>
    </header>
    <main>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul class="flash">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </main>
</body>
</html>

quiz_module_app/templates/quiz_create.html
{% extends 'base.html' %} {% block title %}Create Quiz{% endblock %} {% block
head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<script src="{{ url_for('static', filename='jquery.scrollTo.min.js') }}"></script>
<link href="{{ url_for('static', filename='styleCreateQuiz.css') }}" rel="stylesheet">

{% endblock %} {% block content %}
<a href="#" class="scrollup"></a>
<div class="container">
  <h1>STWÓRZ SWÓJ QUIZ</h1>
  <form>
    {{ form.hidden_tag() }}
    <div class="form-group">
      <h3>{{ form.title.label }}</h3>
      {{ form.title(class="form-control", placeholder="Wpisz tytuł Quizu") }}
    </div>
    <div class="form-group">
      <h3>{{ form.description.label }}</h3>
      {{ form.description(class="form-control", placeholder="Wpisz opis Quizu") }}
    </div>
    <form>
      <button
        id="add-answer"
        type="button"
        class="btn-primary"
        onclick="addAnswer(this.form)"
      >
        Dodaj odpowiedź
      </button>
      <button
        id="add-question"
        type="button"
        class="btn-primary"
        onclick="addQuestion(this.form)"
      >
        Dodaj pytanie
      </button>
      <div name="questions_container"></div>
    </form>
    <script>
      var questionId = 0;
      var answerId = 0;
      var questions_arr = [];
      var answers_arr = [];

      // This is the response array that will contain object with quiz title
      // and description, array with all the questions and array with answers
      var response_arr = [];

      function addQuiz(form) {
        for (var i = 1; i <= questionId; i++) {
          var question = document.getElementsByName("question_" + i)[0];
          if (question) {
            questions_arr.push({
              id: i,
              question_text: question.value,
            });
          }
          var answersText = document.getElementsByName(
            "answer_to_question_" + i
          );
          var answersCheckbox = document.getElementsByName(
            "checkbox_to_question_" + i
          );
          for (var j = 0; j <= answersText.length; j++) {
            var isAnswerCorrect = 0;
            answerText = answersText[j];
            answerCheckbox = answersCheckbox[j];
            if (answerText) {
              answers_arr.push({
                answerToQuestion: i,
                answer_text: answerText.value,
                is_correct: answerCheckbox.getAttribute("isItTrue"),
              });
            }
          }
        }

        var titleText = document.getElementById("title").value;
        var descriptionText = document.getElementById("description").value;
        response_arr.push({ title: titleText, description: descriptionText});
        response_arr.push(questions_arr);
        response_arr.push(answers_arr);
        var xhr = new XMLHttpRequest();
        xhr.open("POST", "{{ url_for('main.add_quiz_json') }}");
        xhr.setRequestHeader("Content-Type", "application/json");
        xhr.onload = function () {
          if (xhr.status === 200) {
            alert("Success!");
          } else {
            alert("Request failed.  Returned status of " + xhr.status);
          }
        };

        xhr.onreadystatechange = function () {
          if (xhr.readyState == XMLHttpRequest.DONE && xhr.status == 200) {
            window.location.href = "/";
          }
        };

        xhr.send(JSON.stringify(response_arr));
      }

      function addAnswer(form) {
        answerId++;
        let newAnswer = document.createElement("textarea");
        let br = document.createElement("br");
        let isItTrue = document.createElement("input");

          newAnswer.setAttribute("name", "answer_to_question_" + questionId);
          newAnswer.setAttribute("class", "answerClass");
        isItTrue.setAttribute("type", "checkbox");
        isItTrue.setAttribute("name", "checkbox_to_question_" + questionId);
        isItTrue.setAttribute(
          "id",
          "chk_" + answerId + "_to_question_" + questionId
        );
        isItTrue.setAttribute(
          "value",
          "chk_" + answerId + "_to_question_" + questionId
        );
        isItTrue.setAttribute("class", "isItTrueClass");
        isItTrue.setAttribute("isItTrue", 0);
        isItTrue.addEventListener("change", (event) => {
          if (event.currentTarget.checked) {
            isItTrue.setAttribute("isItTrue", 1);
          } else {
            isItTrue.setAttribute("isItTrue", 0);
          }
        });


        document.getElementsByName("questionContainer_" + questionId)[0]
           .appendChild(br);
        document
          .getElementsByName("questionContainer_" + questionId)[0]
          .appendChild(newAnswer);
        document
          .getElementsByName("questionContainer_" + questionId)[0]
              .appendChild(isItTrue);

        answersCount++;
        answerId++;
      }

      function checkThisBox(checkbox) {
        console.log("checkThisBox");
      }

      // Add a new question field when the "Add Question" button is clicked
      function addQuestion(form) {
        answerId = 0;
        questionId++;

        var singleQuestionContainer = document.createElement("div");
        singleQuestionContainer.setAttribute(
          "name",
          "questionContainer_" + questionId
        );
        
        var br = document.createElement("br");
        singleQuestionContainer.appendChild(br);

        let newQuestion = document.createElement("textarea");
        newQuestion.setAttribute("name", "question_" + questionId);
        newQuestion.setAttribute("class", "questionClass");
        singleQuestionContainer.appendChild(newQuestion);
        document
          .getElementsByName("questions_container")[0]
          .appendChild(singleQuestionContainer);
        document.appendChild(br);

        var question_text = form.elements["question_text"].value;
        var myArray = [question_text];
      }
    </script>
    <br />
    <br />
    <button
      id="create-quiz-btn"
      type="button"
      class="btn-primary"
      onclick="addQuiz(this.form)"
    >
      Dodaj Quiz
    </button>
  </form>
</div>
{% endblock %}

quiz_module_app/templates/quiz_edit.html
{% extends 'base.html' %}

{% block head%}
<link href="{{ url_for('static', filename='styleEditQuiz.css') }}" rel="stylesheet">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<script src="{{ url_for('static', filename='jquery.scrollTo.min.js') }}"></script>
{% endblock %}

{% block content %}
<a href="#" class="scrollup"></a>
<div class="container">
    <form action="{{ url_for('main.edit_quiz',quiz_id_parameter=quiz.id) }}"
          method="POST">
        <holder id="{{quiz.id}}"></holder>
        <h1>Edytuj quiz</h1>
        <h3>Tytuł</h3>
        <textarea name="quizTitle">{{quiz.title}}</textarea>
        <h3>Opis</h3>
        <textarea name="quizDescription">{{quiz.description}}</textarea>

        {% if questions|length < 1 %}
        <h3 style="text-align: center">Quiz nie zawiera pytań</h3>

        {% else %}
        <table>
            <h3>Pytania</h3>
            {% for question in questions %}
            <tr>
                <td colspan="2"><textarea class="textareaQuestion" name="questionText{{question.id}}">{{ question.text }}</textarea></td>
            </tr>
            {% for answer in question.answers %}
            <tr>
                <td><textarea class="textareaAnswer" name="answerText{{answer.id}}">{{ answer.text }}</textarea></td>
                <td>

                    <label for={{question.id}} class="hidden"></label>
                    {% if answer.is_correct is true %}
                    <input type="checkbox" name="answerBox{{answer.id}}" value="1" class="answerBox" checked="checked" />
                    {% else %}
                    <input type="checkbox" name="answerBox{{answer.id}}" value="1" class="answerBox" />
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
            <tr>
                <td>  </td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}

        <h1>Zakończ edytowanie!</h1>

        <input type="button"
               id="cancel_editing_btn"
               name="cancel_editing_btn"
               value="<< Powrót" />
        <input type="button"
               id="finsih_deleting_btn"
               name="finsih_deleting_btn"
               value="Usuń quiz" />
        <input type="submit"
               name="finish_editing_btn"
               value="Zapisz zmiany" />
    </form>
</div>
<script>
    $('#cancel_editing_btn').click(function () {
        window.location.href = "{{ url_for('main.index') }}";
    });

    $('#finsih_deleting_btn').click(function () {
        let confirmAction = confirm("Czy na pewno chcesz usunąć ten quiz?");
        if (confirmAction) {
            var id = document.getElementsByTagName("holder")[0].id
            alert("Quiz usunięty");
            window.location.href = "/delete/quiz/" + id;
        } else {
            alert("Anulowano usunięcie quizu");
        }
    });


    jQuery(function ($) {
        $.scrollTo(0);


        $('#link3').click(function () { $.scrollTo($('.container'), 500); });
        $('.scrollup').click(function () { $.scrollTo($('body'), 1000); });
    }
    );

    $(window).scroll(
        function () {
            if ($(this).scrollTop() > 300) $('.scrollup').fadeIn();
            else $('.scrollup').fadeOut();
        }
    );
</script>
{% endblock %}

quiz_module_app/templates/solve_quiz.html
{% extends 'base.html' %} {% block title %}Solve Quiz{% endblock %} {% block
head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<script src="{{ url_for('static', filename='jquery.scrollTo.min.js') }}"></script>

{% endblock %} {% block content %}
<div class="content">
  <form
    action="{{ url_for('main.solve_quiz',quiz_id_parameter=quiz.id) }}"
    method="POST"
  >
    <h1>{{quiz.title}}</h1>
    <p>{{quiz.description}}</p>
    {% if questions|length < 1 %}
    <h4 style="text-align: center">Nie ma żadnych pytań. Gratulacje zdałeś!</h4>
    {% else %}
    <table>
      <h1 style="text-align: left">Pytania</h1>
      <tr>
        <th>Treść</th>
      </tr>
      {% for question in questions %}
      <tr>
        <td>{{ question.text }}</td>
      </tr>
      <tr></tr>
      <tr>
        <th>Odpowiedzi:</th>
      </tr>
      <tr>
        <th>Treść</th>
      </tr>
      {% for answer in question.answers %}
      <tr>
        <td>{{ answer.text }}</td>
        <td>
          <br />
          <label for="{{question.id}}"></label><br />
          <input type="checkbox" name="{{question.id}}" value="{{answer.id}}" />
          <br />
        </td>
      </tr>
      {% endfor %} {% endfor %}
    </table>
    {% endif %}

    <br />
    <br />
    <input
      type="submit"
      name="finish_solving_btn"
      value="Zakończ rozwiązywanie"
    />
  </form>
</div>
{% endblock %}